###
POST https://honeynutcheerios.2w7sp317.workers.dev/
Content-Type: application/json

{
  "ipaddress": "192.168.1.1",
	"country": "usa",
	"currentUrl": "https://www.google.com",
	"referringUrl": "https://www.yahoo.com",
	"data": {
		"hello": "world"
	}
}
###


GET http://localhost:4200/assets/quiz/general-physics.json

###


GET https://ipinfo.io/json?token=61c154777637f4

###
